### ISSUE TITLE
Where does node_modules/nodeos-barebones/node_modules go during build?

### ISSUE THREAD

**Issue by timmbrooks** [NodeOS/NodeOS#218] opened 2016-03-08 02:03 UTC
IDK what is going on:

```
$ find . -name adjustEnvVars.sh
./node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/scripts/adjustEnvVars.sh

$ npm install

> NodeOS@0.0.0 install /home/tbrooks/Projects/nodeos
> scripts/build

scripts/build: line 7: /home/myprofile/Projects/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/scripts/adjustEnvVars.sh: No such file or directory

npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! NodeOS@0.0.0 install: `scripts/build`
npm ERR! Exit status 1
npm ERR! etc...

$ find . -name adjustEnvVars.sh
$ 

```
Any clues?

**Comment by piranna** [comment] 2016-03-08 04:29
Npm 3 is not supported, downgrade to npm 2 or use Node.js 4.x. This is a known bug due to npm 2 plain dependencies, hope when nodeos-crosstools is an independent module this gets fixed. Any help here is welcome.

**Comment by piranna** [comment] 2016-06-12 00:55
master now don't have the cross-toolchain inside barebones but instead it's an independent module, and also I'm improved the support of having the dependencies anywhere, could you be able to check again if it works with npm 3?

**Comment by timmbrooks** [comment] 2016-06-12 01:08
Good to hear.  I'm traveling but will be able to pull and test tomorrow.  Will advise.

**Comment by lite20** [comment] 2016-06-12 02:35
I'd run the test but am likely to hit errors not even related to npm3's existence

**Comment by timmbrooks** [comment] 2016-06-13 02:20
I got to build.  I had to step into nodeos-rootfs, -usersfs, -barebones, -initramfs and do 'npm install' separate (I didn't find anything in 'out' directory) and for -usersfs I had to 'npm rebuild'.  When using npm start after everything built, I kept getting qemu error: 
`qemu-system-x86_64: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory`

but I could start up with: 
`qemu-system-x86_64 -enable-kvm -vga std -m 256M -redir tcp:50080::80 -redir tcp:50443::443 --kernel out/latest/barebones --initrd out/latest/initramfs -hda out/latest/usersfs`
and ended up with a REPL.

So I think this specific issue is resolved for npm 3, but there may be something else going on.  Will leave to you if this should be closed.

**Comment by piranna** [comment] 2016-06-13 08:51
Well, these are good news... sort of :-)

The problem on this issue (cross-toolchain was disappearing) is fixed since now the cross-toolchain is an independent module, but NodeOS build system is not yet npm3 ready because they changed the lifecycle and now it seems the `install` step is only executed once when installing a module, but no more when it's finally installed in place. Could you be able to check what's the npm3 lifecycle and if there's some scripts executed when a module is installed? I'll try to do it myself here too to compare.

The QEmu error is unrelated to npm3, it seems it's more related to a system libraries problem, so maybe we could fix it by compiling QEmu itself statically. What do you think?

**Comment by piranna** [comment] 2016-06-14 08:48
I have just check it and confirmed: npm3 only execute `preinstall`, `install`, `postinstall` and `prepublish` scripts on the root project, not its dependencies, so it's assumed that once a dependency is installed its "frozen" and in a good state.

This will make us change the build process, but hopefully not so bad, mostly use `install` script to only download the dependencies and later do the build itself on its own script (`build` is a good candidate :-) ) by executing `npm run build`, and from it call the `build` scripts of the needed dependencies. Ugly, I know, but seems to be the only way... On the other hand, this would allow us to define an argument to set the path where the objects and products will be stored, instead of have them inside the dependency layers folders, what do you think?

**Comment by timmbrooks** [comment] 2016-06-14 17:13
Sorry I didn't get to this.  I spent a little extra time.  Last effort worked:

npm install && npm rebuild && npm install
I haven't investigated much the build process, but firing install after rebuild does something.  Perhaps this might suggest a workaround?  Perhaps this also is paraphrasing what you suggest as well.

**Comment by piranna** [comment] 2016-06-14 17:24
Sort of. On npm2 sometimes I got problems because dependencies are not
fully installed before one module start to install, so executing 'npm
install --ignore-dependencies' first so everything is correctly downloaded
fix it. The same way, by splitting the install and build steps will have in
general the same behaviour, so I think this is the way to go.

**Comment by piranna** [comment] 2016-06-27 11:56
Fixed in master by using npm3 natively, clossing.

**Closed by piranna** 2016-06-27 11:56 UTC
