### ISSUE TITLE
rss feed is broken

### ISSUE THREAD

**Issue by JLLeitschuh** [NodeOS/NodeOS#171] opened 2015-09-22 22:57 UTC
Throws an error
http://pipes.yahoo.com/pipes/pipe.run?_id=d98a965ba7d3f6555b939d707b18dc39&_render=rss&label=blog&owner=NodeOS&repo=NodeOS

**Comment by piranna** [comment] 2015-09-22 23:25
It's working to me, could you be able to recheck?

**Comment by JLLeitschuh** [comment] 2015-09-24 15:20
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<rss xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:media="http://search.yahoo.com/mrss/" xmlns:yt="http://gdata.youtube.com/schemas/2007" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>Copy of Github Issues to RSS</title>
<description>
Put in a Github username and repository name and you get back an RSS feed of its last 30 issues.
</description>
<link>
http://pipes.yahoo.com/pipes/pipe.info?_id=d98a965ba7d3f6555b939d707b18dc39
</link>
<atom:link rel="next" href="http://pipes.yahoo.com/pipes/pipe.run?_id=d98a965ba7d3f6555b939d707b18dc39&_render=rss&page=2"/>
<pubDate>Thu, 24 Sep 2015 15:19:44 +0000</pubDate>
<generator>http://pipes.yahoo.com/pipes/</generator>
</channel>
</rss>
<!--
 fe5.yql.bf1.yahoo.com compressed/chunked Thu Sep 24 15:19:44 UTC 2015 
-->
```
Experiencing with Chrome on OSX.

**Comment by piranna** [comment] 2015-09-24 15:44
It's strange, it's working for me on Firefox/Ubuntu, but it shouldn't matter... How/where are you trying to use the RSS feed?

**Comment by JLLeitschuh** [comment] 2015-09-24 16:17
Clicking on the link on this site: http://node-os.com/

**Comment by aulvi** [comment] 2015-09-24 18:33
Hello @JLLeitschuh, sorry you are having trouble with the rss feed.

Unfortunately, I cannot reproduce the issue on any device I own (linux + chrome, linux + ff, osx + chrome, android + chrome). I'm wondering if maybe we just have different expectations about what "working" looks like.

Here is a screenshot, I consider this to be "working": http://imgur.com/dH6fzla

If you could post a screenshot so we can see the issue as you see it, that would be fantastic.

Thanks!

**Comment by piranna** [comment] 2015-09-24 18:54
> Here is a screenshot, I consider this to be "working": http://imgur.com/dH6fzla

I think so, for me this is "working", too... @JLLeitschuh, that "ugly" XML is the content of the feed, later it's shown "pretty" by your RSS reader... maybe that's what you were expecting?

P.D.: @aulvi, if you send the messages from GitHub you can include the images directly on the issue just by drag&drop, so not only they can be seen directly on GitHub and the emails but also you don't need to do the step to include the image url, too ;-)

**Comment by aulvi** [comment] 2015-09-24 19:02
@piranna Thanks for the reminder, I have updated my comment.

lol "what is dragon drop?"

**Comment by piranna** [comment] 2015-09-24 19:06
> @piranna Thanks for the reminder, I have updated my comment.

You are welcome :-)


> lol "what is dragon drop?"

"dragon drop"? Did you read this? :-P Drag&drop is the shortcut for "drag and drop", it's said, in this case drag a file from the desktop and drop it inside (an area of) the browser. Html5 magic, you know... :-P

**Comment by piranna** [comment] 2015-10-30 11:34
I've just discovered that Yahoo! Pipes [closed last August 31st](http://readwrite.com/2015/06/08/yahoo-shuts-down-pipes), so we now need to find another mechanism to provide the RSS feed :-(

**Comment by piranna** [comment] 2016-02-27 13:16
New RSS feed is available at https://zapier.com/engine/rss/956964/nodeos-blog, so I'm going to close this issue. If there are more problems with it don't worry on re-opening it.

**Closed by piranna** 2016-02-27 13:16 UTC
