### ISSUE TITLE
browser display server

### ISSUE THREAD

**Issue by 5paceManSpiff** [NodeOS/NodeOS#117] opened 2015-03-21 06:40 UTC
i think it would be really cool to use something like [atom-shell](/atom/atom-shell) to create a universal display server completely run on html and javascript injections

**Comment by netlovers** [comment] 2015-03-21 12:37
Check out this thread: https://github.com/NodeOS/NodeOS/issues/79

**Comment by piranna** [comment] 2015-03-21 12:38
Clossing as duplicate of #79

**Closed by piranna** 2015-03-21 12:38 UTC

**Comment by 5paceManSpiff** [comment] 2015-03-21 12:40
thanks!
