### ISSUE TITLE
Entering "?" in at the prompt causing runtime exception.

### ISSUE THREAD

**Issue by JawjLindo** [NodeOS/NodeOS#193] opened 2015-12-22 19:26 UTC
When you start a fresh docker container (with -it), entering a question mark and pressing enter will cause a runtime exception due to a parsing error.
Used image ID: 44628f22098b

**Comment by piranna** [comment] 2015-12-22 19:56
What's the expected behaviour?

**Comment by Compynerd255** [comment] 2015-12-22 20:32
Does this cause node to terminate? Or does it just complain at you and go back to the REPL?

**Comment by lite20** [comment] 2016-02-28 06:10
When entering "?" on the QEMU build it simply bugs that the input is invalid, and prompts you to log back in again and continues as normal. Since docker is no longer supported and this issue isn't occurring I'm closing this thread.

**Closed by lite20** 2016-02-28 06:10 UTC
